name = "k9sitecg"
pages_build_output_dir = "."
compatibility_date = "2025-09-27"

[[env.production.d1_databases]]
database_id = "97b70e72-63b3-4196-8f07-e1f9e9e789bd"
binding = "DB"
database_name = "DB"

[[env.production.r2_buckets]]
bucket_name = "k9-vision-media"
binding = "MEDIA_BUCKET"
